- name: Create MySQL database for WordPress
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for WordPress
  mysql_user:
    name: wp_user
    password: "{{ mysql_wp_password }}"
    priv: 'wordpress.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

