- name: Configure WordPress on WSL
  hosts: localhost
  become: yes
  tasks:

    - name: Update APT package manager
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - unzip
          - curl
        state: present

    - name: Enable Apache mod_rewrite
      command: a2enmod rewrite
      become: yes

    - name: Configure Apache to listen on port 8081
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80$'
        line: 'Listen 8081'
        state: present

    - name: Update VirtualHost to use port 8081
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:8081>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html

            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions for WordPress directory
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Create MySQL database for WordPress
      mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: luka123

    - name: Create MySQL user for WordPress
      mysql_user:
        name: wp_user
        password: wp_pass
        priv: 'wordpress.*:ALL'
        state: present
        login_user: root
        login_password: luka123

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

  handlers:
    - name: Start Apache
      service:
        name: apache2
        state: started

    - name: Start MySQL
      service:
        name: mysql
        state: started

